"""add onboarding_completed to users

Revision ID: 195460f0e641
Revises: 3b7027f89880
Create Date: 2026-05-11 16:56:13.714093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195460f0e641'
down_revision: Union[str, Sequence[str], None] = '3b7027f89880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
