"""add rewrites and summary_rewrite to assay_reports

Revision ID: fd2c6a31a97a
Revises: 63f6722611ae
Create Date: 2026-05-18 16:15:29.609472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd2c6a31a97a'
down_revision: Union[str, Sequence[str], None] = '63f6722611ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assay_reports', sa.Column('rewrites', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default='[]',))
    op.add_column('assay_reports', sa.Column('summary_rewrite', sa.Text(), nullable=True, server_default='',))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assay_reports', 'summary_rewrite')
    op.drop_column('assay_reports', 'rewrites')
    # ### end Alembic commands ###
